# Generated by Django 2.2.15 on 2020-08-11 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proffy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='proffy',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='proffy.Proffys'),
            preserve_default=False,
        ),
    ]
